spring:
  application:
    name: ecom-application

  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: SAniCA2803
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8082
