spring:
  application:
    name: ecom-application

  datasource:
    url: jdbc:postgresql://localhost:5432/eco-microservices
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8082
